# https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

# todo:
# https://docs.github.com/en/actions/guides/building-and-testing-python
# https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows

name: unittest_pytest_coverage_doc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-1804_test_doc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies (ubuntu packages)
      run: sudo apt install python3-fusepy python3-pytest python3-pytest-cov python3-pytest-xdist python3-setuptools git-annex python3-sphinx python3-sphinx-argparse python3-recommonmark latexmk texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
    - name: setup author identity for git commits
      run: |
        test -n "$(git config user.name)" || git config --global user.name $USER
        hostname=$HOSTNAME
        test -n "$hostname" || hostname="runner"
        test -n "$(git config user.email)" || git config --global user.email $(git config user.name)@$hostname
    - name: local unittest
      run: env python3 setup.py run_unittest --src local
    - name: local pytest
      run: env python3 setup.py run_pytest --src local
    - name: install fuse_git_bare_fs
      run: pip3 install .
    - name: unittest
      run: env python3 setup.py run_unittest
    - name: pytest
      run: env python3 setup.py run_pytest --parallel --coverage
    - name: build doc
      run: ./create_doc
    - name: adapt doc fo jekyll
      if: ${{ github.event_name == 'push' }}
      run: touch manual_fuse_git_bare_fs_html/.nojekyll
    - name: deploy pages
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: documentation
        folder: manual_fuse_git_bare_fs_html

  ubuntu-2004_test_doc:
#    runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies (ubuntu packages)
      run: sudo apt install python3-fusepy python3-pytest python3-pytest-cov python3-pytest-xdist python3-setuptools git-annex python3-sphinx python3-sphinx-argparse python3-recommonmark latexmk texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
    - name: setup author identity for git commits
      run: |
        test -n "$(git config user.name)" || git config --global user.name $USER
        hostname=$HOSTNAME
        test -n "$hostname" || hostname="runner"
        test -n "$(git config user.email)" || git config --global user.email $(git config user.name)@$hostname
    - name: local unittest
      run: env python3 setup.py run_unittest --src local
    - name: local pytest
      run: env python3 setup.py run_pytest --src local
    - name: install fuse_git_bare_fs
      run: pip3 install .
    - name: unittest
      run: env python3 setup.py run_unittest
    - name: pytest
      run: env python3 setup.py run_pytest --parallel --coverage
    - name: build doc
      run: ./create_doc
